name: fdas

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres_db_18
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data

    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka_broker
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
        - ./tmp/kafka_data:/kafka/data

  temporal:
    image: temporalio/temporal:1.5.1
    container_name: temporal
    command: [ "server", "start-dev", "--ip", "0.0.0.0" ]
    volumes:
      - ./tmp/temporal_data:/var/lib/temporal
    ports:
      - "7233:7233" # Temporal Frontend gRPC port
      - "8233:8233" # Temporal Web UI port

  opensearch:
    image: opensearchproject/opensearch:3.3.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD="Demo@123"
      - plugins.security.disabled=true   # Disable security for local/testing
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - ./tmp/opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
 
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.3.0
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

