spring:
  application:
    name: demo
  datasource:
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    enable.metrics.push: false
  openai:
    api:
      key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_API_BASE_URL:https://api.openai.com/v1}
    model: ${OPENAI_MODEL:gpt-4o-mini}
    embedding:
      model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-large}
  opensearch:
    host: ${OPENSEARCH_HOST:localhost}
    port: ${OPENSEARCH_PORT:9200}
    scheme: ${OPENSEARCH_SCHEME:http}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_ISSUER_URI:http://localhost:6969/realms/fdsa/protocol/openid-connect/certs}
springdoc:
  swagger-ui:
    oauth:
      client-id: fdsa-backend
      use-pkce-with-authorization-code-grant: true
  OAuthFlow:
    authorizationUrl: ${OAUTH2_AUTHORIZATION_URL:http://localhost:6969/realms/fdsa/protocol/openid-connect/auth}
    tokenUrl: ${OAUTH2_TOKEN_URL:http://localhost:6969/realms/fdsa/protocol/openid-connect/token}
