spring:
  application:
    name: demo
  datasource:
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    enable.metrics.push: false
  temporal:
    url: ${TEMPORAL_URL:localhost:7233}
    namespace: ${TEMPORAL_NAMESPACE:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_ISSUER_URI:http://localhost:6969/realms/fdsa/protocol/openid-connect/certs}
springdoc:
  swagger-ui:
    oauth:
      client-id: fdsa-backend
      use-pkce-with-authorization-code-grant: true
  OAuthFlow:
    authorizationUrl: ${OAUTH2_AUTHORIZATION_URL:http://localhost:6969/realms/fdsa/protocol/openid-connect/auth}
    tokenUrl: ${OAUTH2_TOKEN_URL:http://localhost:6969/realms/fdsa/protocol/openid-connect/token}
